# Generated by Django 2.0.7 on 2018-07-31 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStampedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='images.TimeStampedModel')),
                ('message', models.TextField()),
            ],
            bases=('images.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='images.TimeStampedModel')),
                ('file', models.ImageField(upload_to='')),
                ('locations', models.CharField(max_length=140)),
                ('caption', models.TextField()),
            ],
            bases=('images.timestampedmodel',),
        ),
    ]
