# Generated by Django 2.0.7 on 2018-08-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='delete_soon',
            field=models.BooleanField(default=False),
        ),
    ]
